export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'
export const CREATE_SHOW_SUCCESS = 'CREATE_SHOW_SUCCESS'
export const GET_SHOW_SUCCESS = 'GET_SHOW_SUCCESS'
